parameters:
  - name: env
    type: object
    default:
    - environment: 'dev'
    - environment: 'test'
    - environment: 'acc'
    - environment: 'prod'
  - name: var1
  - name: var2
  - name: nameIt

stages:
- ${{ each ev in parameters.env }}:
  - stage: ${{ ev.environment }}
    displayName: "${{ ev.environment }}"

    jobs:
    - template: job_template.yml
      parameters:
        JobName: "${{ ev.environment }}_work"
        environment_job: "${{ ev.environment }}"