parameters:
  - name: env
    type: object
    default:
    - environment: 'dev'
    - environment: 'test'
  - name: var1
  - name: var2
  - name: nameIt

stages:
- ${{ each ev in parameters.env }}:
  - stage: ${{ ev.environment }}
    displayName: "${{ ev.environment }}"

    jobs:
    - template: thetemplates/job_template.yml@GenericTemplates
      parameters:
        JobName: "${{ ev.environment }}_work"
        environment_job: "${{ ev.environment }}"