name: '$(Build.DefinitionName)-$(Build.SourceBranchName)-$(Date:dd-MM-yyyy)-$(Rev:r)'

trigger: none

resources:
  repositories:
    - repository: GenericTemplates
      type: git
      name: <OrganizationName>/Templates
      ref: refs/heads/main

parameters:
  - name: Name
    displayName: What is your name?
    type: string
    default: 'NoName'
  - name: Var2
    displayName: Give me something!
    type: string
    default: 'theValue'

variables:
- template: vars/vars.yml@GenericTemplates

stages:
- template: thetemplates/stage_template.yml@GenericTemplates
  parameters:
    var1: $(var1)
    var2: ${{ parameters.Var2 }}
    nameIt: ${{ parameters.Name }}
